services:
app:
image: bellsoft/liberica-openjdk-alpine:11.0.16.1-1
command: javac -sourcepath /app/src/main/java -d /app/out /app/src/main/java/st/example/Main.java
volumes:
  - ./bin:/app/out
  - ./src:/app/src